name: traffic-dqn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - pip:
    - tensorflow==2.13.0
    - torch==2.0.1
    - gymnasium==0.29.1
    - stable-baselines3==2.1.0
    - plotly==5.15.0
    - shap==0.42.1
    - traci==1.18.0
    - sumolib==1.18.0
    - streamlit==1.25.0
    - gradio==3.35.2
    - pytest==7.4.0
    - pytest-cov==4.1.0
    - black==23.7.0
    - flake8==6.0.0
    - tqdm==4.65.0
    - pyyaml==6.0.1
    - click==8.1.7
    - python-dotenv==1.0.0
    - wandb==0.15.8
    - tensorboard==2.13.0
    - opencv-python==4.8.0.76
    - pillow==10.0.0
    - networkx==3.1
